name: Run Web Test
run-name: On Push - Web Tests Run
on: [push]

jobs:
  web-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Node.js 19.1
        uses: actions/setup-node@v3
        with:
          node-version: '19.1'

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt
          sudo npm install @playwright/test
          sudo npx playwright install-deps
          rfbrowser init

      - name: Run Robot Framework Web Tests
        run: |
          robot -d ./logs -v HEADLESS:true -v BROWSER:chromium tests

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logs-chromium
          path: ./logs
          if-no-files-found: ignore
          retention-days: 2
          
          
